### PR TITLE
Add support for multiple schema blocks

### PR DESCRIPTION
**Pull request by tjmw**
Add support for multiple schema blocks, either within the same class definition, or inheritable across a class hierarchy. For example a child serializer, which allows us to append/override previously defined schema attributes:

```ruby
class SlimUserSerializer < Oat::Serializer
  adapter Oat::Adapters::HAL

  schema do
    property :name, item.short_name
    property :email, item.email
  end
end

class FullUserSerializer < SlimUserSerializer
  schema do
    property :name, item.full_name
    property :dob, item.dob
  end
end
```

`SlimUserSerializer` will produce output like:

```json
{
  "name": "Homer",
  "email": "homer.j.simpson@example.com"
}
```

`FullUserSerializer` will produce output like:

```json
{
  "name": "Homer Jay Simpson",
  "email": "homer.j.simpson@example.com",
  "dob": "1955-05-12"
}
```

Depending on the adaptor, existing data may be added to or overwritten. For example with the HAL adaptor an entity with a given name will always override any previous entity already defined with the same name. With the Siren adaptor, it will be added to the list of existing entities (assuming it’s not a complete duplicate of another sub-entity).

Note: this does not include the refactoring we talked about offline. I think this is useful on its own.

### CODE REVIEW

**Comment by tjmw** [comment]
Oh weird, not sure why the Travis build is failing. Travis isn't showing me any detail right now. I'll investigate.

**Comment by ismasan** [comment]
👍  after specs are green. Thanks!

**Comment by tjmw** [comment]
Thanks! Those 1.8 spec failures are now fixed. Want me to squash these commits before merging? Or are they okay as they are?

**Comment by ismasan** [comment]
Merging and releasing!

**Pull request merged**
